blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, BlogUpdateView, BlogDeleteView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from .view import homeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')), 
    path('', homeView.as_view(), name='home'),
]

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    status = models.BooleanField(default=True)  # True for published, False for draft
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'content']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
        }
        labels = {
            'title': 'Titulo',
            'content': 'Contenido',
        }

    

blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib import messages
from django.views import View
from .forms import PostForm
from .models import Post


# Create your views here.
class BlogCreateView(View):

    def get(self, request):
        # Renderizar el formulario para crear un nuevo post
        form = PostForm()
        context = {
            'form': form
        }
        return render(request, 'blog_create.html', context)

    def post(self, request):

        if request.method == 'POST':
    
            form = PostForm(request.POST)

            if form.is_valid():
                # Extraer los datos del formulario
                # y crear el objeto Post
                titulo = form.cleaned_data['title']
                contenido = form.cleaned_data['content']

                p, created = Post.objects.get_or_create(
                    title=titulo,
                    content=contenido
                )
                messages.success(request, 'El post se envió correctamente.')
                return redirect('blog:blog_list')

        # Si el formulario no es válido, se vuelve a mostrar el formulario con los errores
        context = {
            'form': form
        }

        return render(request, 'blog_create.html', context)


class BlogListView(View):

    def get(self, request):
        posts = Post.objects.all().order_by('-created_at')
        context = {
            'posts': posts
        }
        return render(request, 'blog_list.html', context)
    
class BlogUpdateView(View):
    def get(self, request, pk):
        post = Post.objects.get(pk=pk)
        form = PostForm(instance=post)
        context = {
            'form': form,
            'post': post
        }
        return render(request, 'blog_create.html', context)

    def post(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            form.save()
            messages.info(request, 'El post se actualizó correctamente.')
            return redirect('blog:blog_list')

        context = {
            'form': form,
            'post': post
        }
        return render(request, 'blog_create.html', context)

class BlogDeleteView(View):
    def get(self, request, pk):
        post = get_object_or_404(Post, pk=pk)
        post.status = False
        post.save()
        messages.warning(request, 'El post se eliminó correctamente.')
        return redirect('blog:blog_list')

blog/templates/blog_create.html
{% extends 'base.html' %}
{% load static %}

{% block navbar%}
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="/"></a>
        </div>
    </nav>
{% endblock %}

{% block section %}
    <div class="container mt-5 mb-15">
        <br>
        <br>
        <br>
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Crear Post</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <form method="post" action="{% if post.pk %}{% url 'blog:blog_update' post.pk %}{% else %}{% url 'blog:blog_create' %}{% endif %}">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary center">{% if post.pk %}Actualizar{% else %}Crear Post{% endif %}</button>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/blog_list.html
{% extends 'base.html' %}
{% load static %}

{% block navbar%}
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="/">Start Bootstrap</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    {% comment %} <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'blog:blog_list' %}">Post</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">About</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Contact</a></li> {% endcomment %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block section%}
    <div class="container mt-5  mb-15">
        <br>
        <br>
        <br>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert" id="mensaje">
                {{ message }}
                </div>
            {% endfor %}
        {% endif %}

        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Lista de Posts</h2>
        <!-- Icon Divider-->
        <a href="{% url 'blog:blog_create' %}"><button type="button" class="btn btn-primary">Crear Post</button></a>
        <div class="divider-custom">
            
            <table class="table">
                <thead>
                    <tr>
                    <th scope="col">#</th>
                    <th scope="col">titulo</th>
                    <th scope="col">Contenido</th>
                    <th scope="col">Fecha</th>
                    <th scope="col">Opciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for post in posts %} 
                        {% if post.status %}
                            <tr>
                                
                                    <th scope="row">{{ forloop.counter }}</th>
                                    <td>{{ post.title }}</td>
                                    <td>{{ post.content }}</td>
                                    <td>{{ post.created_at|date:"Y-m-d H:i" }}</td>
                                    <td>
                                        <a href="{% url 'blog:blog_update' post.id %}" class="btn btn-warning btn-sm">Editar</a>
                                        <a href="{% url 'blog:blog_delete' post.id %}" class="btn btn-danger btn-sm">Eliminar</a>
                                    </td>
                            </tr>
                        {% endif %}
                    {% empty %}
                        <tr>
                            <td colspan="4" class="text-center">No hay posts disponibles.</td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{%block js%}
    <script>
        setTimeout(function (){
            let mensajes = document.querySelectorAll('.alert');
            mensajes.forEach(function (msg){
                msg.classList.remove('show');
                msg.classList.add('hide');
            });
        }, 3000);
    </script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block navbar%}
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="/">Start Bootstrap</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'blog:blog_list' %}">Post</a></li>
                    {% comment %} <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#about">About</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="#contact">Contact</a></li> {% endcomment %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block header %}
    <header class="masthead bg-primary text-white text-center">
        <div class="container d-flex align-items-center flex-column">
            <!-- Masthead Avatar Image-->
            <img class="masthead-avatar mb-5" src="{% static 'assets/img/avataaars.svg' %}" alt="..." />
            <!-- Masthead Heading-->
            <h1 class="masthead-heading text-uppercase mb-0">Pagina Web de Post</h1>
            <!-- Icon Divider-->
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
            <!-- Masthead Subheading-->
            <p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p>
        </div>
    </header>
{% endblock %}